"""empty message

Revision ID: c22037bd6206
Revises: 9e6f6578ca84
Create Date: 2023-10-05 10:34:48.969574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22037bd6206'
down_revision = '9e6f6578ca84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mode')
    # ### end Alembic commands ###
